version: "2.1"
services:
  busy:
    container_name: busy 
    image: busybox
    command: ls -la test-data
    volumes:
      - samplevolume:/test-data # reference to volume from volumes

volumes:
  samplevolume:
    name: test-volume # name of the ebs volume created in aws
    driver: rexray/ebs:0.11.2